"""initial PostgreSQL schema

Revision ID: 954b309b5ead
Revises: 
Create Date: 2026-08-23 09:41:52.061630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954b309b5ead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymized_text', sa.String(length=1000), nullable=False),
    sa.Column('proposed_intent', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_intent', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='learning_candidate_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_candidate_status'), ['status'], unique=False)

    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('dataset_version', sa.String(length=80), nullable=False),
    sa.Column('validation_accuracy', sa.Float(), nullable=True),
    sa.Column('safety_tests_passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('candidate', 'validated', 'current', 'archived', 'failed')", name='model_version_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_path'),
    sa.UniqueConstraint('version')
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_version_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=3000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mood', sa.String(length=30), nullable=False),
    sa.Column('content', sa.String(length=3000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    op.drop_table('chat_message')
    op.drop_table('user')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_version_status'))

    op.drop_table('model_version')
    with op.batch_alter_table('learning_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_candidate_status'))

    op.drop_table('learning_candidate')
    # ### end Alembic commands ###
